name: Publishing svelte-iconor
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
              # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'

            - run: npm install -g pnpm
            # Install dependencies
            - run: pnpm install --frozen-lockfile

            - run: pnpm generate:icons

            - run: pnpm build
            # Publish to npm
            - run: pnpm publish --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

            # Setup .npmrc file to publish to GitHub Packages
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@indaco'

            # Publish to GitHub Packages
            - run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
